### ISSUE TITLE
Baseline Header/Footer

### ISSUE THREAD

**Issue by BMcSpillin** [BMcSpillin/ServeProtect#1]
Create a header/footer in HTML to use across the site on all pages

**Comment by BMcSpillin** [comment]
Anton, the font is named after you! You like?

**Comment by AntEco** [comment]
Love it!

**Comment by AntEco** [comment]
The image has a bigger height than the nav bar.

**Comment by AntEco** [comment]
Looks like the nav bar and footer are good on all 3 pages. Closing this issue.
